### PR TITLE
feat: Update `fastify` to expose API for `HEAD` requests.

### PR DESCRIPTION
**Pull request by hsubra89**
This patch enables a fastify config to enable `HEAD` requests. Readiness and liveness checks should respond correctly to `HEAD` requests since only the status codes are usually relevant for checking the status of services via tools like curl.

Eg:

https://hub.docker.com/r/stefanevinance/wait-for-200/
https://github.com/stefan-evinance/wait-for-200

Tests have been updated to verify this behaviour.

### CODE REVIEW

**Comment by hsubra89-swyftx** [comment]
@gajus, This is currently blocking me from using the latest version of lightship. If merged, could you consider releasing a minor or patch revision?

**Comment by hsubra89** [comment]
@gajus This is currently blocking me from using the latest version of lightship. If merged, could you consider releasing a minor or patch revision?

**Comment by hsubra89** [comment]
@gajus Any update on this please?

**Comment by gajus** [comment]
Sometimes notifications get lost :-(

Looking at this now

**Pull request closed without merging**
