### PR TITLE
fix: override module to "CommonJS" for cjs distribution

### PR DESCRIPTION
**Pull request by fooku18**
see https://github.com/gajus/lightship/issues/67

### CODE REVIEW

**Comment by newerton** [comment]
@fooku18 resolves the conflict and updates the PR

**Comment by dariusdev** [comment]
@gajus  can you give some love for us here or this project is deprecated?

**Comment by gajus** [comment]
This is already in the tsconfig, so I don't see what this PR is trying to accomplish?

https://github.com/gajus/lightship/blob/0a57cc6d128f898c55a4877face8fadb50b89422/tsconfig.build-cjs.json#L3

**Comment by dariusdev** [comment]
All commonJs users cant use this package. I guess this PR should be related with https://github.com/gajus/lightship/issues/69

**Pull request closed without merging**
